image: Visual Studio 2019
skip_commits:
  message: /docs|Merge pull request.*/
init:
  - choco install googlechrome --ignorechecksum
  - npm i -D playwright@1.13.1
build_script:
- ps: >-
    dotnet build src --configuration Release

    dotnet test src --configuration Release --no-build --no-restore
on_failure:
  - ps: Get-ChildItem *.received.* -recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
test: off
artifacts:
- path: nugets\*.nupkg