<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Magick.NET-Q16-AnyCPU" Version="14.17.2" />
    <PackageVersion Include="MarkdownSnippets.MsBuild" Version="28.5.0" />
    <PackageVersion Include="Microsoft.AspNetCore.TestHost" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Playwright" Version="1.63.0" />
    <PackageVersion Include="ProjectDefaults" Version="1.0.184" />
    <PackageVersion Include="PuppeteerSharp" Version="25.12.0" />
    <PackageVersion Include="Sbom" Version="0.3.1" />
    <PackageVersion Include="Selenium.WebDriver" Version="4.51.0" />
    <PackageVersion Include="Selenium.WebDriver.ChromeDriver" Version="155.0.8059.3900" />
    <PackageVersion Include="Verify" Version="33.3.3" />
    <PackageVersion Include="Verify.AngleSharp" Version="5.1.2" />
    <PackageVersion Include="Verify.ImageMagick" Version="4.0.0" />
    <PackageVersion Include="Verify.TUnit" Version="33.3.3" />
    <PackageVersion Include="TUnit" Version="1.73.19" />
    <!-- explicit to avoid a cve -->
    <PackageVersion Include="System.Text.Json" Version="10.0.12" />
    <PackageVersion Include="Argon" Version="0.38.2" />
    <PackageVersion Include="DiffEngine" Version="20.8.1" />
    <PackageVersion Include="EmptyFiles" Version="8.20.1" />
    <PackageVersion Include="SimpleInfoName" Version="3.2.1" />
  </ItemGroup>
</Project>
